[build]
  base = "client"
  command = "npm run build"
  publish = "client/public"
[functions]
  directory = "/server/netlify/functions"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"